### ISSUE TITLE
huggingface login fail

### ISSUE THREAD

**Issue by bentito** [containers/ramalama#465]
The docs say:
```bash
ramalama login --token=XYZ huggingface
```

I try on an m2 macbook pro running python 3.13.0:

```bash
$ ramalama login --token=$HF_TOKEN huggingface
os.execvp(None, [None, 'login', 'huggingface'])
Traceback (most recent call last):
  File "/opt/homebrew/bin/ramalama", line 92, in <module>
    main(sys.argv[1:])
    ~~~~^^^^^^^^^^^^^^
  File "/opt/homebrew/bin/ramalama", line 67, in main
    args.func(args)
    ~~~~~~~~~^^^^^^
  File "/Users/btofel/.local/pipx/venvs/ramalama/lib/python3.13/site-packages/ramalama/cli.py", line 284, in login_cli
    return model.login(args)
           ~~~~~~~~~~~^^^^^^
  File "/Users/btofel/.local/pipx/venvs/ramalama/lib/python3.13/site-packages/ramalama/oci.py", line 70, in login
    return exec_cmd(conman_args, debug=args.debug)
  File "/Users/btofel/.local/pipx/venvs/ramalama/lib/python3.13/site-packages/ramalama/common.py", line 75, in exec_cmd
    return os.execvp(args[0], args)
           ~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 611, in execvp
  File "<frozen os>", line 633, in _execvpe
  File "<frozen posixpath>", line 177, in dirname
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
I confirmed the env var is set to my token as expected. I also tried just putting my token on the CLI. No joy.

**Comment by bentito** [comment]
I confirmed latest ramalama:

```bash
$ pipx upgrade ramalama
ramalama is already at latest version 0.1.1 (location: /Users/btofel/.local/pipx/venvs/ramalama)
```

**Comment by rhatdan** [comment]
Thanks @bentito working on a fix.
