### ISSUE TITLE
'ramalama ps' returns exception on macOS when no container-based llms are running

### ISSUE THREAD

**Issue by planetf1** [containers/ramalama#488]
On macOS Sonama I have one model running. This appears not to be running as a container but is working well, with Apple Silicon metal/gpu support. `podman ps` shows a variety of other containers (of mine) running, but no llms from ralalama

The command should not hit an exception - either it should report that no containers are running, or -- better -- would be to include any non-container llms being served. In my case that is
```
  501 27676  1627   0  4:35pm ttys021    0:00.80 llama-server --port 9999 -m /Users/jonesn/.local/share/ramalama/models/ollama/llama3.1:8b --host 0.0.0.0
```

Here's the failing command:
```
~ ramalama ps
Traceback (most recent call last):
  File "/opt/homebrew/bin/ramalama", line 92, in <module>
    main(sys.argv[1:])
    ~~~~^^^^^^^^^^^^^^
  File "/opt/homebrew/bin/ramalama", line 67, in main
    args.func(args)
    ~~~~~~~~~^^^^^^
  File "/opt/homebrew/share/ramalama/ramalama/cli.py", line 390, in list_containers
    if len(_list_containers(args)) == 0:
           ~~~~~~~~~~~~~~~~^^^^^^
  File "/opt/homebrew/share/ramalama/ramalama/cli.py", line 380, in _list_containers
    output = run_cmd(conman_args).stdout.decode("utf-8").strip()
             ~~~~~~~^^^^^^^^^^^^^
  File "/opt/homebrew/share/ramalama/ramalama/common.py", line 96, in run_cmd
    return subprocess.run(args, check=True, cwd=cwd, stdout=stdout, stderr=stderr)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/subprocess.py", line 554, in run
    with Popen(*popenargs, **kwargs) as process:
         ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/subprocess.py", line 1036, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        pass_fds, cwd, env,
                        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
                        gid, gids, uid, umask,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        start_new_session, process_group)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/subprocess.py", line 1837, in _execute_child
    and os.path.dirname(executable)
        ~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "<frozen posixpath>", line 177, in dirname
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by ericcurtin** [comment]
And we should try and make this technique portable so that it works across macOS and Linux (whilst adding no dependancies). If we must we can do:

if macos:
  do this
else if linux and not using containers:
  do this

**Comment by rhatdan** [comment]
Did you have neither docker podman installed?

**Comment by planetf1** [comment]
Just rechecked with the latest ramalama code, and get the same result.

Both `podman ps` and `docker ps` return a list of currently running containers (though none relate to ramalama)

**Comment by planetf1** [comment]
So looking at detection, [this line](https://github.com/containers/ramalama/blob/6c837315e4a5ac10b69b6f43282d8fd8b6b7889d/ramalama/common.py#L37) seems to be problematic

since

```
➜  ramalama git:(main) podman machine list --format '{{ .VMType }}'
applehv
```

I'm not familar with *krunkit* - and am using podman desktop 1.15. That being said podman was originally installed (and still is) via homebrew, so there may be some discrepancy here? (though all seems to work)

**Comment by planetf1** [comment]
I can confirm that with a krunkit vm ramalama works without further configuration.

In my case the confusion arose from having installed podman via 'homebrew' prior to podman desktop. So many macOS users make use of homebrew, so I imagine that's quite typical. This distribution doesn't seem to include krunkit (not sure if that may change, or if versions specific, though mine was up to date)

Secondly, krunkit isn't the default, even when using podman desktop - though it is easy to select.

I would suggest that there's several options
- minimum would just be to document this clearly
- appropriate imo would be to allow ramalama to work as long as podman/docker found 
 - even better would be to add a warning/message if you find the vm isn't accelerated

**Comment by ericcurtin** [comment]
> I can confirm that with a krunkit vm ramalama works without further configuration.
> 
> In my case the confusion arose from having installed podman via 'homebrew' prior to podman desktop. So many macOS users make use of homebrew, so I imagine that's quite typical. This distribution doesn't seem to include krunkit (not sure if that may change, or if versions specific, though mine was up to date)
> 
> Secondly, krunkit isn't the default, even when using podman desktop - though it is easy to select.
> 
> I would suggest that there's several options
> 
> * minimum would just be to document this clearly
> * appropriate imo would be to allow ramalama to work as long as podman/docker found

It's not really a sufficient check because if podman machine isn't started:

```
$ podman ps
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: failed to connect: ssh: handshake failed: read tcp 127.0.0.1:55279->127.0.0.1:51791: read: connection reset by peer
```

> * even better would be to add a warning/message if you find the vm isn't accelerated

**Comment by ericcurtin** [comment]
This should fix part of the issue:

https://github.com/containers/ramalama/pull/557

**Comment by ericcurtin** [comment]
This is slightly better:

https://github.com/containers/ramalama/pull/604

**Comment by ericcurtin** [comment]
It prints this now:

Error: no container manager (Podman, Docker) found
