### ISSUE TITLE
ramalama requirements needs to add llama-cli or equivalent tool

### ISSUE THREAD

**Issue by smooge** [containers/ramalama#496]
I found this while trying to debug https://bugzilla.redhat.com/show_bug.cgi?id=2329826

```
[ssmoogen@xenadu ~]$ ramalama --debug --nocontainer run granite "What is Fedora?"
exec_cmd:  llama-cli -m /home/ssmoogen/.local/share/ramalama/models/huggingface/ibm-granite/granite-8b-code-instruct-GGUF/granite-8b-code-instruct.Q4_K_M.gguf --in-prefix  --in-suffix  -p What is Fedora? -c 2048
os.execvp(llama-cli, ['llama-cli', '-m', '/home/ssmoogen/.local/share/ramalama/models/huggingface/ibm-granite/granite-8b-code-instruct-GGUF/granite-8b-code-instruct.Q4_K_M.gguf', '--in-prefix', '', '--in-suffix', '', '-p', 'What is Fedora?', '-c', '2048'])
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/ramalama/model.py", line 292, in run
    exec_cmd(exec_args, args.debug, debug=args.debug)
  File "/usr/lib/python3.12/site-packages/ramalama/common.py", line 75, in exec_cmd
    return os.execvp(args[0], args)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 609, in execvp
  File "<frozen os>", line 651, in _execvpe
  File "<frozen os>", line 642, in _execvpe
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ramalama", line 92, in <module>
    main(sys.argv[1:])
  File "/usr/bin/ramalama", line 67, in main
    args.func(args)
  File "/usr/lib/python3.12/site-packages/ramalama/cli.py", line 610, in run_cli
    model.run(args)
  File "/usr/lib/python3.12/site-packages/ramalama/model.py", line 296, in run
    raise NotImplementedError(file_not_found % (exec_args[0], exec_args[0], exec_args[0], str(e).strip("'")))
                              ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: not all arguments converted during string formatting
```

I missed this when packaging up ramalama for Fedora so I guess there is something needed in `requirements.txt` or similar so people would know that python-llama_cli was needed.

**Comment by rhatdan** [comment]
We should catch this error, llama-cli(llama.cpp)should only be a recommends.
